# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'IDCard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'SVProgressHUD', '~> 2.0.3'

  target 'IDCardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
